config/routes.rb
ThumbsUp::Application.routes.draw do
  get '/rows/(:path)', to: 'rows#index'
  namespace :admin do
    root to: 'rows#index'
    resources :rows do
      resources :thumbs, except: [:index]
    end
  end

end

app/models/row.rb
class Row < ActiveRecord::Base
  has_many :thumbs, dependent: :destroy
  validates :title, presence: true
end

app/models/thumb.rb
class Thumb < ActiveRecord::Base
  VALID_LABEL_REGEX = /\A[a-zA-Z0-9\- ]+\z/i

  belongs_to :row

  validates :label, presence: true, length: { maximum: 20 }, format: { with: VALID_LABEL_REGEX }

  def slug
    self.label.gsub(/\s/, '-').downcase
  end

end

app/controllers/admin/rows_controller.rb
class Admin::RowsController < ApplicationController
  before_action :get_row, only: [:show, :edit, :update, :destroy]

  def index
    @rows = Row.all
  end

  def show
  end

  def new
    @row = Row.new
  end

  def create
    @row = Row.new(row_params)
    if @row.save
      redirect_to admin_rows_path
    else
      redirect_to new_admin_row_path
    end
  end

  def edit
  end

  def update
    if @row.update(row_params)
      redirect_to [:admin, @row]
    else
      redirect_to edit_admin_row_path(@row)
    end
  end

  def destroy
    @row.destroy
    redirect_to admin_rows_path
  end

  private

    def get_row
      @row = Row.find(params[:id])
    end

    def row_params
      params.require(:row).permit(:title, :description, :link_url)
    end
end

app/controllers/admin/thumbs_controller.rb
class Admin::ThumbsController < ApplicationController
  before_action :get_row
  before_action :get_thumb, only: [:show, :edit, :update, :destroy]

  def show
  end

  def edit
  end

  def update
    if @thumb.update(thumb_params)
      redirect_to [:admin, @row, @thumb]
    else
      render 'edit'
    end
  end

  def new
    @thumb = @row.thumbs.new
  end

  def create
    @thumb = @row.thumbs.new(thumb_params)
    if @thumb.save
      redirect_to [:admin, @row]
    else
      render 'edit'
    end
  end

  def destroy
    @thumb.destroy
    redirect_to [:admin, @row]
  end

  private

    def get_row
      @row = Row.find(params[:row_id])
    end

    def get_thumb
      @thumb = @row.thumbs.find(params[:id])
    end

    def thumb_params
      params.require(:thumb).permit(:label, :image_path, :active)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rows_controller.rb
class RowsController < ApplicationController
  def index
    @rows = Row.all
  end
end

app/controllers/thumbs_controller.rb
class ThumbsController < ApplicationController
  before_action :get_row
  before_action :get_thumb, only: [:show, :edit, :update, :destroy]

  def show
  end

  def edit
  end

  def update
    if @thumb.update(thumb_params)
      redirect_to [@row, @thumb]
    else
      render 'edit'
    end
  end

  def new
    @thumb = @row.thumbs.new
  end

  def create
    @thumb = @row.thumbs.new(thumb_params)
    if @thumb.save
      redirect_to @row
    else
      render 'edit'
    end
  end

  def destroy
    @thumb.destroy
    redirect_to row_path(@row)
  end

  private

    def get_row
      @row = Row.find(params[:row_id])
    end

    def get_thumb
      @thumb = @row.thumbs.find(params[:id])
    end

    def thumb_params
      params.require(:thumb).permit(:label, :image_path, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rows_helper.rb
module RowsHelper
end

app/helpers/thumbs_helper.rb
module ThumbsHelper
end

app/views/admin/rows/_form.html.erb
<%= form_for([:admin, @row]) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :link_url %>
    <%= f.text_field :link_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/rows/_row.html.erb
<%= div_for row, style: 'padding-left: 50px;' do %>
  <%= link_to "#{row.title}", [:admin, row] %>
  <%= link_to '(edit)', edit_admin_row_path(row) %>
  <%= link_to '(delete)', [:admin, row], method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/admin/rows/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= content_tag :h1, "Edit Row##{@row.id}" %>
    <%= render 'admin/rows/form' %>
  </div>
</div>

app/views/admin/rows/index.html.erb
<h1>Rows</h1>

<div class="rows">
  <%= render @rows %>
</div>

<%= link_to 'Create new row', new_admin_row_path %>

app/views/admin/rows/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= content_tag :h1, "New row" %>
    <%= render 'admin/rows/form' %>
  </div>
</div>

app/views/admin/rows/show.html.erb
<%= content_tag :h1, "View Row##{@row.id}" %>
<p>Title: <%= @row.title %></p>
<p>Description:<br><%= @row.description %></p>
<p>Link url: <%= @row.link_url %></p>

<%= link_to 'Edit Row', edit_admin_row_path(@row) %>

<%= content_tag :h3, "Row thumbs" %>

<div class="thumbs">
  <%= render @row.thumbs %>
</div>

<%= link_to 'Create new thumb', new_admin_row_thumb_path(@row) %>

app/views/admin/thumbs/_form.html.erb
<%= form_for([:admin, @row, @thumb]) do |f| %>
  <div class="field">
    <%= f.label :label %>
    <%= f.text_field :label %>
  </div>

  <div class="field">
    <%= f.label :image_path %>
    <%= f.text_field :image_path %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/thumbs/_thumb.html.erb
<%= div_for thumb do %>
  <%= link_to "View #{thumb.label}", [:admin, @row, thumb] %>
  <%= link_to '(edit)', edit_admin_row_thumb_path(@row, thumb) %>
  <%= link_to '(delete)', [:admin, @row, thumb], method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/admin/thumbs/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= content_tag(:h1, "Edit thumb for row ##{@row.id}") %>
    <%= render 'admin/thumbs/form' %>
  </div>
</div>

app/views/admin/thumbs/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= content_tag(:h1, "New thumb for row ##{@row.id}") %>
    <%= render 'admin/thumbs/form' %>
  </div>
</div>

app/views/admin/thumbs/show.html.erb
<%= content_tag(:h2, "Viewing thumb ##{@thumb.id} for row ##{@row.id}") %>

<p>Label: <%= @thumb.label %></p>
<p>Image Path: <%= @thumb.image_path %></p>
<p>Active: <%= (@thumb.active) ? 'Yes' : 'No' %> </p>

<%= link_to 'Edit Thumb', edit_admin_row_thumb_path %>
<%= link_to 'Delete Thumb', [:admin, @row, @thumb], method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>ThumbsUp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/rows/_form.html.erb
<%= form_for(@row) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :link_url %>
    <%= f.text_field :link_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rows/_row.html.erb
<%= div_for row, class: 'thumb-row rel clearfix' do %>
  <%= render row.thumbs %>
  <div class="rel thumb-carousel-container rec-zone">
    <a href="#" class="close-button"><span>close</span></a>
    <div class="rel rs-carousel" style="width:870px; padding-top: 20px;">
      <ul>
        <li>
          <div class="rel" style="height: 400px; width: 870px;">
            <div class="abs" style="left: 50px; top: 50px">
              <%= image_tag asset_path('image_placeholder.jpg') %>
            </div>
            <div class="abs" style="left: 364px; top: 84px">
              <p style="font-size: 60px; font-weight: bold;">BALL</p>
            </div>
            <div class="abs" style="left: 364px; top: 31px">
              <p style="font-size: 60px; font-weight: normal;">BEACH</p>
            </div>
            <div class="abs" style="left: 364px; top: 190px">
              <p style="font-size: 14px; font-weight: bold;">THE DETAILS WOULD GO HERE...</p>
            </div>
            <div class="abs" style="left: 364px; top: 250px">
              <a href="http://www.foo.com">Foo Bar Link</a>
            </div>
          </div>
        </li>
        <li>
          <div class="rel" style="height: 400px; width: 870px;">
            <div class="abs" style="left: 50px; top: 50px">
              <%= image_tag asset_path('image_placeholder.jpg') %>
            </div>
            <div class="abs" style="left: 364px; top: 84px">
              <p style="font-size: 60px; font-weight: bold;">CASTLE</p>
            </div>
            <div class="abs" style="left: 364px; top: 31px">
              <p style="font-size: 60px; font-weight: normal;">SAND</p>
            </div>
            <div class="abs" style="left: 364px; top: 190px">
              <p style="font-size: 14px; font-weight: bold;">THE DETAILS WOULD GO HERE...</p>
            </div>
            <div class="abs" style="left: 364px; top: 250px">
              <a href="http://www.foo.com">Foo Bar Link</a>
            </div>
          </div>
        </li>
        <li>
          <div class="rel" style="height: 400px; width: 870px;">
            <div class="abs" style="left: 50px; top: 50px">
              <%= image_tag asset_path('image_placeholder.jpg') %>
            </div>
            <div class="abs" style="left: 364px; top: 84px">
              <p style="font-size: 60px; font-weight: bold;">SOUP</p>
            </div>
            <div class="abs" style="left: 364px; top: 31px">
              <p style="font-size: 60px; font-weight: normal;">TURTLE</p>
            </div>
            <div class="abs" style="left: 364px; top: 190px">
              <p style="font-size: 14px; font-weight: bold;">THE DETAILS WOULD GO HERE...</p>
            </div>
            <div class="abs" style="left: 364px; top: 250px">
              <a href="http://www.foo.com">Foo Bar Link</a>
            </div>
          </div>
        </li>
        <li>
          <div class="rel" style="height: 400px; width: 870px;">
            <div class="abs" style="left: 50px; top: 50px">
              <%= image_tag asset_path('image_placeholder.jpg') %>
            </div>
            <div class="abs" style="left: 364px; top: 84px">
              <p style="font-size: 60px; font-weight: bold;">KONG</p>
            </div>
            <div class="abs" style="left: 364px; top: 31px">
              <p style="font-size: 60px; font-weight: normal;">DONKEY</p>
            </div>
            <div class="abs" style="left: 364px; top: 190px">
              <p style="font-size: 14px; font-weight: bold;">THE DETAILS WOULD GO HERE...</p>
            </div>
            <div class="abs" style="left: 364px; top: 250px">
              <a href="http://www.foo.com">Foo Bar Link</a>
            </div>
          </div>
        </li>
        <li>
          <div class="rel" style="height: 400px; width: 870px;">
            <div class="abs" style="left: 50px; top: 50px">
              <%= image_tag asset_path('image_placeholder.jpg') %>
            </div>
            <div class="abs" style="left: 364px; top: 84px">
              <p style="font-size: 60px; font-weight: bold;">FIGHT</p>
            </div>
            <div class="abs" style="left: 364px; top: 31px">
              <p style="font-size: 60px; font-weight: normal;">CAT</p>
            </div>
            <div class="abs" style="left: 364px; top: 190px">
              <p style="font-size: 14px; font-weight: bold;">THE DETAILS WOULD GO HERE...</p>
            </div>
            <div class="abs" style="left: 364px; top: 250px">
              <a href="http://www.foo.com">Foo Bar Link</a>
            </div>
          </div>
        </li>
        <li>
          <div class="rel" style="height: 400px; width: 870px;">
            <div class="abs" style="left: 50px; top: 50px">
              <%= image_tag asset_path('image_placeholder.jpg') %>
            </div>
            <div class="abs" style="left: 364px; top: 84px">
              <p style="font-size: 60px; font-weight: bold;">MARIO</p>
            </div>
            <div class="abs" style="left: 364px; top: 31px">
              <p style="font-size: 60px; font-weight: normal;">SUPER</p>
            </div>
            <div class="abs" style="left: 364px; top: 190px">
              <p style="font-size: 14px; font-weight: bold;">THE DETAILS WOULD GO HERE...</p>
            </div>
            <div class="abs" style="left: 364px; top: 250px">
              <a href="http://www.foo.com">Foo Bar Link</a>
            </div>
          </div>
        </li>
        <li>
          <div class="rel" style="height: 400px; width: 870px;">
            <div class="abs" style="left: 50px; top: 50px">
              <%= image_tag asset_path('image_placeholder.jpg') %>
            </div>
            <div class="abs" style="left: 364px; top: 84px">
              <p style="font-size: 60px; font-weight: bold;">BOARD</p>
            </div>
            <div class="abs" style="left: 364px; top: 31px">
              <p style="font-size: 60px; font-weight: normal;">WHITE</p>
            </div>
            <div class="abs" style="left: 364px; top: 190px">
              <p style="font-size: 14px; font-weight: bold;">THE DETAILS WOULD GO HERE...</p>
            </div>
            <div class="abs" style="left: 364px; top: 250px">
              <a href="http://www.foo.com">Foo Bar Link</a>
            </div>
          </div>
        </li>
        <li>
          <div class="rel" style="height: 400px; width: 870px;">
            <div class="abs" style="left: 50px; top: 50px">
              <%= image_tag asset_path('image_placeholder.jpg') %>
            </div>
            <div class="abs" style="left: 364px; top: 84px">
              <p style="font-size: 60px; font-weight: bold;">GRASS</p>
            </div>
            <div class="abs" style="left: 364px; top: 31px">
              <p style="font-size: 60px; font-weight: normal;">TALL</p>
            </div>
            <div class="abs" style="left: 364px; top: 190px">
              <p style="font-size: 14px; font-weight: bold;">THE DETAILS WOULD GO HERE...</p>
            </div>
            <div class="abs" style="left: 364px; top: 250px">
              <a href="http://www.foo.com">Foo Bar Link</a>
            </div>
          </div>
        </li>
        <li>
          <div class="rel" style="height: 400px; width: 870px;">
            <div class="abs" style="left: 50px; top: 50px">
              <%= image_tag asset_path('image_placeholder.jpg') %>
            </div>
            <div class="abs" style="left: 364px; top: 84px">
              <p style="font-size: 60px; font-weight: bold;">BATMAN</p>
            </div>
            <div class="abs" style="left: 364px; top: 190px">
              <p style="font-size: 14px; font-weight: bold;">THE DETAILS WOULD GO HERE...</p>
            </div>
            <div class="abs" style="left: 364px; top: 250px">
              <a href="http://www.foo.com">Foo Bar Link</a>
            </div>
          </div>
        </li>
        <li>
          <div class="rel" style="height: 400px; width: 870px;">
            <div class="abs" style="left: 50px; top: 50px">
              <%= image_tag asset_path('image_placeholder.jpg') %>
            </div>
            <div class="abs" style="left: 364px; top: 84px">
              <p style="font-size: 60px; font-weight: bold;">GOBLIN</p>
            </div>
            <div class="abs" style="left: 364px; top: 31px">
              <p style="font-size: 60px; font-weight: normal;">GREEN</p>
            </div>
            <div class="abs" style="left: 364px; top: 190px">
              <p style="font-size: 14px; font-weight: bold;">THE DETAILS WOULD GO HERE...</p>
            </div>
            <div class="abs" style="left: 364px; top: 250px">
              <a href="http://www.foo.com">Foo Bar Link</a>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
<% end %>

app/views/rows/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= content_tag :h1, "Edit Row##{@row.id}" %>
    <%= render 'rows/form' %>
  </div>
</div>

app/views/rows/index.html.erb
<h1>Thumbs Up (click on a thumbnail, dummy)</h1>
<div id="thumb-container">
  <%= render @rows %>
</div>

app/views/rows/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= content_tag :h1, "New row" %>
    <%= render 'rows/form' %>
  </div>
</div>

app/views/rows/show.html.erb
<%= content_tag :h1, "View Row##{@row.id}" %>
<p>Title: <%= @row.title %></p>
<p>Description:<br><%= @row.description %></p>
<p>Link url: <%= @row.link_url %></p>

<%= link_to 'Edit Row', edit_row_path(@row) %>

<%= content_tag :h3, "Row thumbs" %>

<div class="thumbs">
  <%= render @row.thumbs %>
</div>

<%= link_to 'Create new thumb', new_row_thumb_path(@row) %>

app/views/thumbs/_form.html.erb
<%= form_for([@row, @thumb]) do |f| %>
  <div class="field">
    <%= f.label :label %>
    <%= f.text_field :label %>
  </div>

  <div class="field">
    <%= f.label :image_path %>
    <%= f.text_field :image_path %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thumbs/_thumb.html.erb
<%= div_for thumb, 'data-active' => thumb.active, 'data-path' => thumb.slug do |thumb| %>
  <div class="image-wrapper">
    <%= image_tag asset_path('thumb_placeholder.jpg') %>
  </div>
  <%= content_tag :p, thumb.label.upcase, class: 'thumb-label' %>
  <div class="arrow hidden"></div>
<% end %>

app/views/thumbs/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= content_tag(:h1, "Edit thumb for row ##{@row.id}") %>
    <%= render 'thumbs/form' %>
  </div>
</div>

app/views/thumbs/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= content_tag(:h1, "New thumb for row ##{@row.id}") %>
    <%= render 'thumbs/form' %>
  </div>
</div>

app/views/thumbs/show.html.erb
<%= content_tag(:h2, "Viewing thumb ##{@thumb.id} for row ##{@row.id}") %>

<p>Label: <%= @thumb.label %></p>
<p>Image Path: <%= @thumb.image_path %></p>
<p>Active: <%= (@thumb.active) ? 'Yes' : 'No' %> </p>

<%= link_to 'Edit Thumb', edit_row_thumb_path %>
<%= link_to 'Delete Thumb', row_thumb_path(@row, @thumb), method: :delete %>